[package]
name = "deno_typescript"
version = "0.48.2"
license = "MIT"
description = "To compile TypeScript to a snapshot during build.rs"
repository = "https://github.com/denoland/deno"
authors = ["the Deno authors"]
edition = "2018"

exclude = [
  "typescript/tests/*",
  "typescript/src/*",
  "typescript/scripts/*",
  "typescript/doc/*",
  "typescript/lib/*/*.json",
]

[lib]
path = "lib.rs"

[dependencies]
deno_core = { path = "../core", version = "0.48.2" }
serde_json = "1.0.55"
serde = { version = "1.0.112", features = ["derive"] }
