# Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_core"
version = "0.48.2"
edition = "2018"
description = "A secure JavaScript/TypeScript runtime built with V8, Rust, and Tokio"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
downcast-rs = "1.1.1"
futures = { version = "0.3.5", features = ["thread-pool", "compat"] }
lazy_static = "1.4.0"
libc = "0.2.71"
log = "0.4.8"
rusty_v8 = "0.6.0"
serde_json = "1.0.55"
url = "2.1.1"

[[example]]
name = "deno_core_http_bench"
path = "examples/http_bench.rs"

# These dependendencies are only used for deno_core_http_bench.
[dev-dependencies]
derive_deref = "1.1.0"
tokio = { version = "0.2.21", features = ["rt-core", "tcp"] }
