# Got "production" Site Configuration (adds to or overrides "_default")

# Usage notes:
# To build with these settings, you run: "hugo --config production"
# Hugo build then uses every setting defined in "config/_default" and then merge
# all settings defined here for "staging" on top of all those define for "_default".

baseURL = "https://deno-docs.netlify.com/"
enableRobotsTXT = true
